Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DbFirst_one_to_many_crud.Data;
using DbFirst_one_to_many_crud.Models;
using DbFirst_one_to_many_crud.Infrastructure;
using DbFirst_one_to_many_crud.Repository;

namespace DbFirst_one_to_many_crud.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IDepartment _IDepartment;
        public DepartmentsController(AppDbContext context, IDepartment IDepartment)
        {
            _context = context;
            _IDepartment = IDepartment;
        }

        // GET: Departments
        public async Task<IActionResult> Index()
        {
            try
            { 
            var depList = await _context.Departments_jay.ToListAsync();
            if(depList != null)
            {
                return View(depList);
            }
            else
            {
                return null;
            }
            }
            catch(Exception e)
            {
                Logger.Log(e);
                e.Message.ToString();
                result = ($"Dhananjay program exception as  { e.Message.ToString()}");
            }
            return View();
        }
        /*public async Task<IActionResult> Index()
        {
            var items = await _ICategory.GetAllAsync();
            return View(items);

        }*/
        string result = "";
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var item = await _IDepartment.GetByIDAsync(id);
                return View(item);
            }
            catch (Exception e)
            {
                Logger.Log(e);
                result =($"Dhananjay program exception as  { e.Message.ToString()}");
            }
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Department department)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _IDepartment.InsertAsync(department);
                    await _IDepartment.SaveAsync();
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Logger.Log(ex);
                result = ($"Dhananjay program exception as  { ex.Message.ToString()}");
            }
            return View();
        }
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                Department cat = await _IDepartment.GetByIDAsync(id);
                return View(cat);
            }
            catch (Exception e)
            {
                Logger.Log(e);
                result = ($"Dhananjay program exception as  { e.Message.ToString()}");
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Department department)
        {
            try
            {
                await _IDepartment.UpdateAsync(department);
                await _IDepartment.SaveAsync();
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                Logger.Log(e);
                result = ($"Dhananjay program exception as  { e.Message.ToString()}");
            }
            return View();
        }
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _IDepartment.DeleteAsync(id);
                await _IDepartment.SaveAsync();
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                e.Message.ToString();
            }
            return View();
        }
    }
}

Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DbFirst_one_to_many_crud.Data;
using DbFirst_one_to_many_crud.Models;

namespace DbFirst_one_to_many_crud.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly AppDbContext _context;
        public readonly Logger _logError;
        public EmployeesController(AppDbContext context)
        {
            _context = context;
            _logError = new Logger(context);
        }
        string result = "";
        // GET: Employees
        public IActionResult Index()
        {
            //return View(await _context.Employees_jay.ToListAsync());
            try
            {
                var stdlist = from e in _context.Employees_jay
                              join d in _context.Departments_jay
                              on e.DepID equals d.DepartmentId
                              into Dep
                              from d in Dep.DefaultIfEmpty()

                              select new Employee
                              {
                                  Id = e.Id,
                                  FirstName = e.FirstName,
                                  LastName = e.LastName,
                                  Email = e.Email,
                                  Mobile = e.Mobile,
                                  Description = e.Description,
                                  DepID = e.DepID,
                                  Department = d == null ? "" : d.DepartmentName
                              };
                if (stdlist != null)
                {
                    return View(stdlist);
                }
                else
                {
                    return null;
                }
            }
            catch (Exception ex)
            {
                Logger.Log(ex);
                ex.Message.ToString();
                result = ($"Dhananjay program exception as  { ex.Message.ToString()}");
            }
            return View();
        }
        public IActionResult IndexAjax()
        {
            Employee emp = new Employee();
            //return View(await _context.Employees_jay.ToListAsync());
            try
            {
                var stdlist = from e in _context.Employees_jay
                              join d in _context.Departments_jay
                              on e.DepID equals d.DepartmentId
                              into Dep
                              from d in Dep.DefaultIfEmpty()

                              select new Employee
                              {
                                  Id = e.Id,
                                  FirstName = e.FirstName,
                                  LastName = e.LastName,
                                  Email = e.Email,
                                  Mobile = e.Mobile,
                                  Description = e.Description,
                                  DepID = e.DepID,
                                  Department = d == null ? "" : d.DepartmentName
                              };
                if (stdlist != null)
                {
                    return View(stdlist);
                }
                else
                {
                    return null;
                }
            }
            catch (Exception ex)
            {
                //Logger.Log(ex);
                ex.Message.ToString();
                //result = ($"Dhananjay program exception as  { ex.Message.ToString()}");
            }
            return View(emp);
        }
        public async Task<IActionResult> Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var employee = await _context.Employees_jay
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (employee == null)
                {
                    return NotFound();
                }

                return View(employee);
            }
            catch (Exception ex)
            {

                /*Logger.Log(ex);
                ex.Message.ToString();
                result = ($"Dhananjay program exception as  { ex.Message.ToString()}");*/
            }
            return View();
        }
        public async Task<IActionResult> ViewEmployee(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var employee = await _context.Employees_jay
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (employee == null)
                {
                    return NotFound();
                }

                //return View(employee);
                return PartialView("_details", employee);
            }
            catch (Exception ex)
            {

                /*Logger.Log(ex);
                ex.Message.ToString();
                result = ($"Dhananjay program exception as  { ex.Message.ToString()}");*/
            }
            return View();
        }
        
        public async Task<IActionResult> EditEmployee(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var employee = await _context.Employees_jay
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (employee == null)
                {
                    return NotFound();
                }

                //return View(employee);
                return PartialView("_Edit", employee);
            }
            catch (Exception ex)
            {

                /*Logger.Log(ex);
                ex.Message.ToString();
                result = ($"Dhananjay program exception as  { ex.Message.ToString()}");*/
            }
            return View();
        }
        
        public async Task<IActionResult> UpdateEmployee(Employee obj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Attach(obj);
                    _context.Entry(obj).State = EntityState.Modified;
                    await _context.SaveChangesAsync();
                    return PartialView("_EmployeeList", obj);
                }
                return View();
            }
            catch (Exception e)
            {
                Logger.Log(e);
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public async Task<IActionResult> DeleteEmployee(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var employee = await _context.Employees_jay
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (employee == null)
                {
                    return NotFound();
                }
                else
                {
                    _context.Entry(employee).State = EntityState.Deleted;
                    await _context.SaveChangesAsync();
                    return Ok();
                }

            }
            catch (Exception ex)
            {
                /*Logger.Log(ex);
                ex.Message.ToString();
                result = ($"Dhananjay program exception as  { ex.Message.ToString()}");*/
            }
            return View();
        }
        [HttpGet]
        public IActionResult AddEmployeeAjax()
        {
            Employee emp = new Employee();
            return PartialView("_AddEmployee", emp);
        }
        [HttpPost]
        public async Task<IActionResult> AddEmployees(Employee obj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (obj.Id == 0)
                    {
                        _context.Employees_jay.Add(obj);
                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                        _context.Entry(obj).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                    }
                    return PartialView("_Message", obj);
                }
                //return View();
            }
            catch (Exception e)
            {
               /* Logger.Log(e);
                return RedirectToAction("Index");*/
            }
            return PartialView("_AddEmployee");
        }
       /* public async Task<IActionResult> AddEmployee(int id = 0)
        {
            if (id == 0)
                return View(new Employee());
            else
            {
                var transactionModel = await _context.Employees_jay.FindAsync(id);
                if (transactionModel == null)
                {
                    return NotFound();
                }
                return View(transactionModel);
            }
        }*/
        [HttpGet]
        public IActionResult Create(Employee obj)
        {
            loadDDL();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEmployee(Employee obj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (obj.Id == 0)
                    {
                        _context.Employees_jay.Add(obj);
                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                        _context.Entry(obj).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                    }
                    return RedirectToAction("Index");

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DbFirst_one_to_many_crud</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/datatables/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <!--  Add following stylesheets to <head> tag  -->
    <link rel="preload" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" data-rocket-async="style" as="style" onload="this.onload=null;this.rel='stylesheet'" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DbFirst_one_to_many_crud</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departments" asp-action="Index">Department</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Emloyee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="IndexAjax">EmloyeeAjax</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <div class="modal fade" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false" id="form-modal">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DbFirst_one_to_many_crud - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>